{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "praxis-gateway.configMapName" . }}
  labels:
    {{- include "praxis-gateway.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}
{{- end }}
